name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x, 26.x, latest]

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Enable Corepack
        run: npm install -g corepack

      - run: corepack yarn install --immutable
      - run: corepack yarn run build
