name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: yarn

      - name: Enable Corepack
        run: npm install -g corepack

      - run: yarn install --immutable
      - run: yarn run biome ci
